apiVersion: v1
kind: Service
metadata:
  name: llamacpp
  namespace: llamacpp
  labels:
    app.kubernetes.io/name: llamacpp
spec:
  # ClusterIP for internal access. Change to LoadBalancer or NodePort for
  # external access, or front with an Ingress resource.
  type: ClusterIP
  selector:
    app.kubernetes.io/name: llamacpp
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
