# Goose Profile with Flox Environment Awareness

# This profile makes Goose aware of Flox environment management
# Copy this to your project's .goose/profiles.yaml

default:
  provider: openai  # or anthropic, ollama, etc.
  processor: gpt-4
  accelerator: gpt-4
  moderator: passive

  # Flox Environment Instructions
  instructions: |
    # Environment Management with Flox

    This project uses **Flox** for reproducible development environments.

    ## Flox Detection

    Check for `.flox/` directory in the project root. If present, this is a Flox-managed project.

    ## Context-Based Flox Documentation

    Before working on specific task types, fetch appropriate Flox documentation:

    ### Task Context Mapping

    | User Request | Context | Command |
    |--------------|---------|---------|
    | Package or build software | Packaging | `./fetch-flox.sh packaging` |
    | Work with Kubernetes | K8s | `./fetch-flox.sh k8s` |
    | Use containers/Docker | Containers | `./fetch-flox.sh containers` |
    | Setup CUDA/GPU | CUDA | `./fetch-flox.sh cuda` |
    | Configure CI/CD | CI/CD | `./fetch-flox.sh cicd` |
    | Local development setup | Local dev | `./fetch-flox.sh local-dev` |
    | Operations/deployment | Ops | `./fetch-flox.sh ops` |

    ## Workflow

    1. User makes a request requiring Flox knowledge
    2. Identify the appropriate context from the mapping table
    3. Run: `./fetch-flox.sh <context>`
    4. Read the downloaded `FLOX.md` file for guidance
    5. Apply Flox best practices from the documentation
    6. Proceed with the user's original request

    ## Fetch Script

    The project should have `fetch-flox.sh` in the root:

    ```bash
    #!/usr/bin/env bash
    set -e

    REPO_OWNER="barstoolbluz"
    REPO_NAME="flox-md"
    FILE_NAME="FLOX.md"

    declare -A BRANCH_NICKNAMES=(
        ["packaging"]="building-and-packaging-with-flox"
        ["k8s"]="flox-and-k8s"
        ["containers"]="flox-and-containers"
        ["cuda"]="flox-and-cuda"
        ["cicd"]="flox-and-ci-cd"
        ["local-dev"]="local-dev-with-flox"
        ["ops"]="ops-with-flox"
    )

    BRANCH_INPUT="${1:-main}"

    if [[ -n "${BRANCH_NICKNAMES[$BRANCH_INPUT]}" ]]; then
        BRANCH="${BRANCH_NICKNAMES[$BRANCH_INPUT]}"
        echo "Using nickname '$BRANCH_INPUT' → branch '$BRANCH'"
    else
        BRANCH="$BRANCH_INPUT"
        echo "Fetching from branch '$BRANCH'"
    fi

    RAW_URL="https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/${BRANCH}/${FILE_NAME}"

    echo "Downloading ${FILE_NAME} from ${RAW_URL}..."
    if curl -fSL "$RAW_URL" -o "${FILE_NAME}"; then
        echo "Successfully saved ${FILE_NAME} to $(pwd)/${FILE_NAME}"
    else
        echo "Error: Failed to fetch ${FILE_NAME} from branch '${BRANCH}'" >&2
        echo "Please verify the branch exists and contains ${FILE_NAME}" >&2
        exit 1
    fi
    ```

    ## Flox Commands

    ```bash
    # Activate environment
    flox activate

    # Install package
    flox install <package>

    # Search for packages
    flox search <package>

    # Show package info
    flox show <package>

    # List installed packages
    flox list

    # Edit manifest
    flox edit
    ```

    ## Core Principles

    - Always check for `.flox/` directory to detect Flox projects
    - Use Flox for all dependencies (not apt, brew, npm globally)
    - Activate environment before development: `flox activate`
    - Fetch context proactively when user's request matches a context type
    - The manifest (`.flox/env/manifest.toml`) is the source of truth
    - Apply Flox best practices from fetched documentation

# Alternative profile using Ollama (local models) with Flox awareness
ollama-local:
  provider: ollama
  processor: qwen2.5-coder:7b
  accelerator: qwen2.5-coder:7b
  moderator: passive

  instructions: |
    # Environment Management with Flox

    This project uses **Flox** for reproducible development environments.

    Check for `.flox/` directory. If present, use Flox for all environment management.

    Before working on specific tasks, fetch appropriate documentation:
    - Packaging: `./fetch-flox.sh packaging`
    - Kubernetes: `./fetch-flox.sh k8s`
    - Containers: `./fetch-flox.sh containers`
    - CUDA/GPU: `./fetch-flox.sh cuda`
    - CI/CD: `./fetch-flox.sh cicd`
    - Local dev: `./fetch-flox.sh local-dev`
    - Operations: `./fetch-flox.sh ops`

    Read the downloaded FLOX.md for context-specific guidance before proceeding.

    Key commands:
    - `flox activate` - Enter environment
    - `flox install <package>` - Add dependency
    - `flox search <query>` - Find packages
    - `flox list` - Show installed packages

    Always use Flox for dependencies instead of system package managers.
